# def say_hello(name):
#     print ("Hello ", name)
#     print ("Aap kaise ho?")
# say_hello("GAURI SUDHAKAR PATIL.")


# def say_hello(name):
#     print("GAURI",name)
#     print("GIRALE")
# say_hello("PATIL")


# def add_numbers(number1, number2):
#     print ("Main do numbers ko add karunga.")
#     print (number1 + number2)
# add_numbers(120, 50)
# num_x = 134
# name = "Rinki"
# print(num_x,name)

