# def calculater(a,b,c):
#     if c=="add":
#         return(a,"aur",b,"ka addition",a+b,"hai")
#     elif c=="multy":
#         return(a,"aur",b,"ka multiplication",a*b,"hai")
#     elif c=="div":
#         return(a,"aur",b,"ka dividion",a%b,"hai")
#     elif c=="substract":
#         return(a,"aur",b,"ka substrstion",a-b,"hai")
# print(calculater(4,5,"substract"))
# print(calculater(3,4,"div"))
# print(calculater(6,7,"multy"))
# print(calculater(2,4,"add"))
    