# def icecream(*flavours):
#      for flavour in flavours:
#          print("i love"+flavour)

# icecream("chocolate", "butterscotch","vanilla","strawberry") 


# def attendance(name,status="absent"):
#     print(name,"is",status," today")

# attendance("kartik","present")
# attendance("sonu")
# attendance("gauri","present")
# attendance("umesh") 


# def greet(*names):
#     for name in names:
#         print("Welcome"+name)
# greet("Rinki", "Vishal", "Kartik", "Bijender") 


# def student(*list_of_student):
#     print(list_of_student)
# student("GAURI","KUSUM","SAGRIKA","SHALINI","KIRTI") 
