# print ("NavGurukul")

# def say_hello():
#     print ("Hello!")
#     print ("Aap kaise ho?")

# say_hello()
# print ("Python is awesome")
# say_hello()
# print ("Hello…")
# say_hello() 
# say_hello()


# def definition_say_hello():
#     print ("NavGurukul")
#     print ("NavGurukul mei humein apni learning ki responsibility leni padti hai.")
# definition_say_hello()
# print ("NavGurukul mei hum sab logo ko ek tarah se treat karte hai.")
# definition_say_hello() 


# def function_say_bye():
#     print ("Aapko mil ke maza aaya. ")
#     print ("Bye bye")
# function_say_bye()
# function_say_bye()
# print ("Python ka istamaal bahot jagah hota hai.")
# function_say_bye()
# function_say_bye() 


# def say_hello_again():
#     print ("Firse Hello :)")
#     print ("Aap kaise ho?") 
# say_hello_again()




# def function_print_lines():
#     print( "Mera naam Rishabh hai.","Main NavGurukul ka co-Founder hun." )
# function_print_lines()





    
    