# delete_nth=[1,1,1,1]
# def remove(a):
#         delete_nth.pop(-1)
# print(delete_nth)
# remove(2)

# def delete(a):
#     list1=[1,1,2,3]
#     i=0
#     while i<len(list1):
#         list1.remove(list1[-i])
#         i=i+1
#     print(list1)
# delete(2)


# list1=[1,1,2,3]
# list2 = []
# num = int(input("number : "))
# length = int(len(list1))
# i = 0
# while i < length-num:
#     list2.append(list1[i])
#     i = i + 1
# print(list2) 

