# def add_numbers_list():
#     add_numbers1=[50,20,10]
#     add_numbers2=[10,60,13]
#     print(add_numbers1[0]+add_numbers2[0])
#     print(add_numbers1[1]+add_numbers2[1])
#     print(add_numbers1[2]+add_numbers2[2])
# add_numbers_list()


# def check_numbers():
#     if 10%2==0 and 6%2==0:
#          print("even hai")
#     else:
#         print("even nahi hai")
# check_numbers()

    # def check_numbers_list(a,b):
#     i=0
#     while i<len(a):
#         s=a[i]
#         j=b[i]
#         if s%2==0 and j%2==0:
#             print("both are even")
#         else:
#             print("both are not even")
#         i=i+1

